### ISSUE TITLE
Error： 'dotnet.exe' has exited with code 0

### ISSUE THREAD

**Issue by Xu-Shihao** [Isaac-W/KinectXEFTools#1]
Hi,

When I debug the code. I met an error like below:

`
'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'I:\Kinect Extractor\KinectXEFTools-master\examples\XEFExtract\bin\Debug\netcoreapp2.1\xefextract.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[18140] dotnet.exe' has exited with code 0 (0x0).
`

I can not find the solution of this issue. I have tried to reinstall all once, but still not help.

Would any one give me some help?

My machine is Windows 10, using Visual Studio 2017.

![image](https://user-images.githubusercontent.com/20655000/55666797-3d5edd80-5886-11e9-9147-ada65f73c184.png)

Thanks!
XU SHIHAO

**Comment by Xu-Shihao** [comment]
Thanks for your help. The issue has been fixed.

**Comment by helenayele** [comment]
How do you get it fixed?

**Comment by ogenefavour** [comment]
how did you get it fixed?
